{% set tpl = ix_lib.base.render.Render(values) %}

{% set c1 = tpl.add_container(values.consts.restic_rest_container_name, "image") %}
{% set perm_container = tpl.deps.perms(values.consts.perms_container_name) %}
{% set perms_config = {"uid": values.run_as.user, "gid": values.run_as.group, "mode": "check"} %}
{% set scheme = "https" if values.network.certificate_id else "http" %}

{% do c1.set_user(values.run_as.user, values.run_as.group) %}

{% do c1.healthcheck.set_test("netcat", {"port": values.consts.internal_web_port}) %}

{% set options_list = [] %}

{% if values.network.certificate_id %}
  {% set _ = options_list.append("--tls --tls-key " ~ values.consts.ssl_key_path ~ " --tls-cert " ~ values.consts.ssl_cert_path) %}
  {% set cert = values.ix_certificates[values.network.certificate_id] %}
  {% do c1.configs.add("p_flagsrivate", cert.privatekey, values.consts.ssl_key_path) %}
  {% do c1.configs.add("public", cert.certificate, values.consts.ssl_cert_path) %}
{% endif %}

{% if values.rest_server_flags.append_only %}
  {% set _ = options_list.append("--append-only") %}
{% endif %}
{% if values.rest_server_flags.group_accessible_repos %}
  {% set _ = options_list.append("--group-accessible-repos") %}
{% endif %}
{% if values.rest_server_flags.no_auth %}
  {% set _ = options_list.append("--no-auth") %}
{% endif %}
{% if values.rest_server_flags.private_repos %}
  {% set _ = options_list.append("--private-repos") %}
{% endif %}

{% set options_env = options_list | join(" ") %}
{% do c1.environment.add_env("OPTIONS", options_env) %}

{% do c1.add_storage(values.consts.data_path, values.storage.data) %}
{% do perm_container.add_or_skip_action("data", values.storage.data, perms_config) %}

{% for store in values.storage.additional_storage %}
  {% do c1.add_storage(store.mount_path, store) %}
  {% do perm_container.add_or_skip_action(store.mount_path, store, perms_config) %}
{% endfor %}

{% if perm_container.has_actions() %}
  {% do perm_container.activate() %}
  {% do c1.depends.add_dependency(values.consts.perms_container_name, "service_completed_successfully") %}
{% endif %}

{% if not values.network.host_network %}
  {% do c1.add_port(values.network.web_port, {"container_port": values.consts.internal_web_port}) %}
{% endif %}

{% do tpl.portals.add(values.network.web_port, {"scheme": scheme}) %}

{{ tpl.render() | tojson }}
