app_version: 0.14.0
capabilities: []
categories:
- backup
changelog_url: https://github.com/restic/restic-rest-server/releases
date_added: '2025-08-22'
description: 'Rest Server is a high performance HTTP server that implements restic''s
  REST backend API. It provides secure and efficient way to backup data remotely,
  using restic backup client via the rest: URL.'
home: https://github.com/restic/rest-server
host_mounts: []
icon: https://media.sys.truenas.net/apps/restic-rest-server/icons/icon.png
keywords:
- backup
- restic
lib_version: 2.1.47
lib_version_hash: 88da92f6a9c3f4b264946906b525cc0684098f50c6c84159a52906bbb827687f
maintainers:
- email: dev@ixsystems.com
  name: truenas
  url: https://www.truenas.com/
name: restic-rest-server
run_as_context:
- description: Restic rest-server runs as any non-root user.
  gid: 568
  group_name: rest-server
  uid: 568
  user_name: rest-server
screenshots: []
sources:
- https://github.com/restic/rest-server
- https://hub.docker.com/r/restic/rest-server
title: Restic REST Server
train: community
version: 0.14.0
