images:
  image:
    repository: restic/rest-server
    tag: 0.14.0

consts:
  restic_rest_container_name: restic-rest
  perms_container_name: permissions
  data_path: /data
  ssl_key_path: /certs/key.pem
  ssl_cert_path: /certs/cert.pem
  htpasswd_path: /auth/htpasswd
